### ISSUE TITLE
ケーブルのモデル

### ISSUE THREAD

**Issue by C6H2Cl2** [Team-Antimatter-Mod/AntiMatterMod#1]
ケーブルのモデルが微妙にずれてるのと、重複によるチラツキがあるので、誰か直して
俺はもうあの作業をやる気が起きない
[こ↑こ↓](https://github.com/Team-Antimatter-Mod/AntiMatterMod/blob/master/src/main/java/antimattaermod/core/Model/CableModel.java)

**Comment by raiti-chan** [comment]
修正完了
[これ](https://github.com/Team-Antimatter-Mod/AntiMatterMod/commit/c31fafa56cfae7531c0b127a2da0019c80408ada)
